[package]
name = "binoxxo"
version = "0.1.0"
authors = ["Martin Suesskraut <martin.suesskraut@gmail.com>"]

[dependencies]
rand = "0.3"
printpdf = "0.2"
if_chain = "0.1.2"

[dev-dependencies]
quickcheck = "0.5"
quickcheck_macros = "0.5"